application: go2service02
version: beta-trees
runtime: python
api_version: 1

default_expiration: "10d"

handlers:

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  
- url: /css
  static_dir: media/css

- url: /js
  static_dir: media/js

- url: /production\.js
  static_files: media/js/production.js
  upload: media/js/production.js
  expiration: "1s"


- url: /images
  static_dir: media/images

- url: /PIE.htc
  static_files: PIE.htc
  upload: PIE.htc
  mime_type: text/x-component

- url: /favicon.png
  static_files: favicon.png
  upload: favicon.png

- url: /admin
  script: main_handler.py
  login: admin

- url: /admin/.*
  script: main_handler.py
  login: admin

- url: /.*
  script: main_handler.py

builtins:
 - datastore_admin: on
 - remote_api: on
