application: go2serviceru
version: beta
runtime: python
api_version: 1

default_expiration: "10d"

handlers:
- url: /css
  static_dir: media/css

- url: /js
  static_dir: media/js

- url: /images
  static_dir: media/images

- url: /PIE.htc
  static_files: PIE.htc
  upload: PIE.htc
  mime_type: text/x-component

- url: /favicon.png
  static_files: favicon.png
  upload: favicon.png

- url: /admin
  script: main_handler.py
  login: admin

- url: /admin/.*
  script: main_handler.py
  login: admin

- url: /.*
  script: main_handler.py
