application: go2serviceru
version: alpha
runtime: python
api_version: 1

default_expiration: "10d"

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /PIE.htc
  static_files: PIE.htc
  upload: PIE.htc
  mime_type: text/x-component

- url: /favicon.png
  static_files: favicon.png
  upload: favicon.png

- url: /
  script: main_handler.py

- url: /media/.*
  script: main_handler.py

- url: /admin
  script: main_handler.py
  login: admin

- url: /admin/.*
  script: main_handler.py
  login: admin


